export const ACTION_TYPE = {
	SEARCH_MOVIE: "SEARCH_MOVIE",
	FETCH_MOVIE: "FETCH_MOVIE",
	FETCH_MOVIES: "FETCH_MOVIES",
	FETCH_SERIES: "FETCH_SERIES",
	FETCH_TRENDING: "FETCH_TRENDING",
	FILTER_GENRE: "FILTER_GENRE",
	FILTER_LANGUAGE: "FILTER_LANGUAGE",
};
